writing_prompts = [
    "You wake up in a world where everyone has superpowers except you.",
    "A detective is on the trail of a thief who can teleport.",
    "You find a diary that predicts the future.",
    "A spaceship lands in your backyard.",
    "You discover a hidden door in your house that leads to another dimension.",
    "A time traveler from the future needs your help.",
    "You inherit a mysterious, ancient artifact with magical powers.",
    "A friendly ghost haunts your new apartment.",
    "You have the ability to speak with animals, and they need your help.",
    "A secret society is trying to recruit you for their cause.",
    "You wake up one day with the ability to read minds.",
    "A scientist offers you a chance to live on Mars.",
    "You find a portal to a parallel universe in your basement.",
    "A stranger hands you a suitcase full of money and a cryptic note.",
    "You discover your best friend is a superhero in disguise.",
    "An ancient prophecy predicts you will save the world.",
    "You meet a future version of yourself who warns you of impending danger.",
    "A machine that grants wishes appears in your living room.",
    "You are the last human on Earth after an alien invasion.",
    "You find a map leading to a hidden treasure beneath your city.",
    "You develop the ability to control the weather.",
    "A genie grants you three wishes, but there are unexpected consequences.",
    "You wake up with no memories and a mysterious tattoo on your arm.",
    "A magical book transports you into its story.",
    "You receive a letter from a long-lost relative inviting you to a hidden island.",
    "You discover you can travel through time using an old pocket watch.",
    "A mysterious illness spreads through your town, and you are immune.",
    "You are chosen to represent humanity in an intergalactic council.",
    "You find a camera that shows you glimpses of the future.",
    "A dragon appears in your backyard and claims you are its rider.",
    "You discover a hidden underground city beneath your town.",
    "You are given a chance to relive one day of your life, but with a twist.",
    "A robot becomes your best friend and protector.",
    "You inherit a haunted mansion and must uncover its secrets.",
    "You find a pair of glasses that allow you to see people's true intentions.",
    "You are transported into your favorite video game and must complete a quest to return home.",
    "A mysterious voice in your head guides you through dangerous situations.",
    "You discover a hidden talent that makes you famous overnight.",
    "You are kidnapped by pirates and must find a way to escape.",
    "You find an ancient tree that grants you wisdom and knowledge.",
    "A famous celebrity asks for your help to solve a mystery.",
]